import { WebhookPayload } from '../types';

export const triggerN8nWorkflow = async (
  webhookUrl: string, 
  payload: WebhookPayload
): Promise<boolean> => {
  if (!webhookUrl) {
    throw new Error("N8n Webhook URL is missing. Please configure it in Settings.");
  }

  try {
    // In a real scenario, we use POST. 
    // For n8n webhooks, ensure you use the 'Production' URL for live use 
    // or 'Test' URL when testing.
    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      throw new Error(`N8n Error: ${response.statusText}`);
    }

    return true;
  } catch (error) {
    console.error("Failed to trigger automation:", error);
    throw error;
  }
};

// This is the JSON Template for the N8n Workflow
export const getN8nWorkflowTemplate = () => {
  return JSON.stringify({
    "nodes": [
      {
        "parameters": {
          "path": "generate-video",
          "responseMode": "lastNode",
          "options": {}
        },
        "name": "Webhook Input",
        "type": "n8n-nodes-base.webhook",
        "typeVersion": 1,
        "position": [100, 300]
      },
      {
        "parameters": {
          "prompt": "={{ $json.body.topic }}",
          "model": "gemini-pro"
        },
        "name": "Gemini Script",
        "type": "n8n-nodes-base.googleGemini",
        "typeVersion": 1,
        "position": [300, 300]
      },
      {
        "parameters": {
          "content": "Generate Video (Placeholder for Veo/Luma API)",
          "height": 400,
          "width": 300
        },
        "name": "Generate Video",
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.1,
        "position": [500, 300]
      },
      {
        "parameters": {
          "conditions": {
            "boolean": [
              {
                "value1": "={{ $json.body.target_platforms.includes('YOUTUBE') }}",
                "value2": true
              }
            ]
          }
        },
        "name": "If YouTube",
        "type": "n8n-nodes-base.if",
        "typeVersion": 1,
        "position": [700, 200]
      },
      {
        "parameters": {
          "authentication": "oAuth2",
          "resource": "video",
          "title": "={{ $json.body.topic }}",
          "description": "Generated by ContentFlow"
        },
        "name": "Upload YouTube",
        "type": "n8n-nodes-base.youtube",
        "typeVersion": 1,
        "position": [900, 100]
      }
    ],
    "connections": {
      "Webhook Input": { "main": [[{ "node": "Gemini Script", "type": "main", "index": 0 }]] },
      "Gemini Script": { "main": [[{ "node": "Generate Video", "type": "main", "index": 0 }]] },
      "Generate Video": { "main": [[{ "node": "If YouTube", "type": "main", "index": 0 }]] },
      "If YouTube": { "main": [[{ "node": "Upload YouTube", "type": "main", "index": 0 }]] }
    }
  }, null, 2);
};